apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 00617f1f5b1823e7b66e19c6ce00ab64dbb1b076
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 00617f1f5b1823e7b66e19c6ce00ab64dbb1b076
