apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 54f8f811e4862579dbfc48ee95fa66587e52e3f9
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 54f8f811e4862579dbfc48ee95fa66587e52e3f9
