apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: playlist-recommender


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: eb9c120f3587b13f6c250adfd483597a092a2c68
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: eb9c120f3587b13f6c250adfd483597a092a2c68
