apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 3166f728fa9838540ae3f9064ed8f111a06a7f65
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 3166f728fa9838540ae3f9064ed8f111a06a7f65
