apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- config_map.yaml

namespace: playlist-recommender


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 82ab23c57a3528717dfcbfae13a067277bbf75a1
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 82ab23c57a3528717dfcbfae13a067277bbf75a1
