apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: d65659fd61edec51a7b1dc46c472aff8b10e117f
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: d65659fd61edec51a7b1dc46c472aff8b10e117f
