apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: playlist-recommender-annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 4a062da7a250d318eae14ccdd9b4169a9d1ae62d
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 4a062da7a250d318eae14ccdd9b4169a9d1ae62d
