apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 610933d6869b021007019c015f10d52501e17642
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 610933d6869b021007019c015f10d52501e17642
