apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

namespace: playlist-recommender-annecarvalho


images:
- name: playlist-recommender-api
  newName: annecarvalho/app_api
  newTag: 3db41bfa93911404152940e390f1dd43f130ffcd
- name: playlist-recommender-ml
  newName: annecarvalho/app_ml
  newTag: 3db41bfa93911404152940e390f1dd43f130ffcd
