apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: playlist-recommender-app
  ports:
    - protocol: TCP
      port: 32168
      targetPort: 32168

---

apiVersion: v1
kind: Service
metadata:
  name: recommender-ml-service
spec:
  selector:
    app: playlist-recommender-ml
  ports:
    - protocol: TCP
      port: 32168
      targetPort: 32168