name: CD
on:
  push:
    branches: [main]
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_repository:
          - annecarvalho/app_api
          - annecarvalho/app_ml
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u annecarvalho --password-stdin

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: annecarvalho
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ matrix.image_repository }}
          tags: |
            ${{ github.event.release.tag_name }},latest
          path: ${{ matrix.image_repository }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build   
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image playlist-recommender-api=annecarvalho/app_api:${{ github.event.release.tag_name }}
          kustomize edit set image playlist-recommender-ml=annecarvalho/app_ml:${{ github.event.release.tag_name }}
          cat kustomization.yaml

      - name: atualizar valor de env
        run: |
          cd k8s
          echo "versao: ${{ github.event.release.tag_name }}" > deployment.yaml
          cat deployment.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master


